version: '3'
services:
  consumer:
    build:
      context: .
      dockerfile: ./docker/consumer/Dockerfile
      args:
        tag: parakafka/consumer
        progress: plain
    deploy:
      replicas: 3
    restart: always
    network_mode: host
    environment:
      BOOTSTRAP_BROKERS: 10.1.8.3:9095 10.1.8.3:9096 10.1.8.3:9097 #note add if needed
      KAFKA_GROUP_ID: test-group
      MONGO_URL: mongodb://10.1.8.2