---
version: '2'
services:
  zookeeper:
    # networks:
    #   - kafka-net
    image: confluentinc/cp-zookeeper:5.0.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    # networks:
    #   - kafka-net
    #   - consumer-net
    image: confluentinc/cp-kafka:5.0.0
    container_name: kafka
    labels:
      - 'custom.project=kafkajs-zstd'
      - 'custom.service=kafka'
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
      CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
  web-hook-server:
    # networks:
    #   - kafka-net
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
      args:
        tag: parakafka/server
        progress: plain

    container_name: web-hook-server
    depends_on:
      - zookeeper
      - kafka
      # - kafka1
      # - kafka2
    ports:
      - '3000:3000'
    restart: always
    environment:
      - BOOTSTRAP_BROKERS=kafka:29092 kafka1:29092 kafka2:29092
