version: '3'
services:
  consumer:
    build:
      context: .
      dockerfile: ./docker/consumer/Dockerfile
      args:
        tag: parakafka/consumer
        progress: plain
    deploy:
      replicas: 3
    restart: always
    network_mode: host
    environment:
      BOOTSTRAP_BROKERS: localhost:9095 localhost:9096 localhost:9097 #note add if needed
      KAFKA_GROUP_ID: test-group
      MONGO_URL: mongodb://localhost