version: '2'
services:
  producer:
    build:
      context: .
      dockerfile: ./docker/producer/Dockerfile
      args:
        tag: parakafka/producer
        progress: plain
    deploy:
      replicas: 3
    restart: always
    network_mode: host
